#!/bin/bash
set -e

# Create jellydiscod user and group if they don't exist
if ! getent group jellydiscod > /dev/null; then
  groupadd -r jellydiscod
fi

if ! getent passwd jellydiscod > /dev/null; then
  useradd -r -g jellydiscod -d /var/lib/jellydiscod -s /usr/sbin/nologin jellydiscod
fi

# Reload systemd
systemctl daemon-reload || true
